import Sidebar from "src/partials/Sidebar";
import Navbar from "src/partials/Navbar";
import Head from "next/head";


export default function Programs() {
    return (
        <>
            <Head>
                <title>Programs</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/programs.svg" />
            </Head>
            <Navbar />
            <Sidebar />
        </>
    )
}