/* eslint-disable @typescript-eslint/no-unsafe-member-access */

/* eslint-disable @typescript-eslint/no-unsafe-argument */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-call */
import Sidebar from 'src/partials/Sidebar';
import Navbar from 'src/partials/Navbar';
import Head from 'next/head';
import Container from 'src/partials/Container';
import InputField from 'src/Components/InputField';
import { useEffect, useState } from 'react';
import Button from 'src/Components/Button';
import { v4 as uuidv4 } from 'uuid';

type InputValues = {
	programName: string;
	year: string;
	duration: string;
	tag: string;
	semesters: [
		{
			id: string;
			semesterName: string;
			courses: [
				{
					id: string;
					courseName: string;
					optional: boolean;
				},
			];
		},
	];
};

export default function NewProgram() {
	return (
		<>
			<Head>
				<title>New Program</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/courses.svg" />
			</Head>
			<Navbar />
			<Sidebar />
			<Container>
				<section className="ml-3 h-full">
					<form className="flex flex-col justify-center px-3 overflow-hidden">
						<span className="inline-flex items-center text-2xl font-medium text-primary-800 dark:text-primary-500">
							<svg
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
								width="20"
								height="20"
								strokeWidth={2}
								stroke="currentColor"
								className="mr-2"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"
								/>
							</svg>
							Add New Program
						</span>
						<div className="px-4 py-5 sm:p-6">
							<div className="grid grid-cols-6 gap-6">
								<InputField
									name="programName"
									className="col-span-6 lg:col-span-6"
									label="Program Name"
									type="text"
								/>
								<InputField
									name="year"
									className="col-span-6 lg:col-span-2"
									label="Year"
									type="text"
								/>
								<InputField
									name="duration"
									className="col-span-6 lg:col-span-2"
									label="Duration"
									type="text"
								/>
								<InputField
									name="tag"
									className="col-span-6 lg:col-span-2"
									label="Tag"
									type="text"
								/>
							</div>
							{/* <Button
								className="mt-3"
								onClick={handleSubmit}
								label="Submit"
							/> */}
						</div>

						<p className="inline-flex items-center text-base font-medium text-primary-800 dark:text-primary-500">
							Semesters
						</p>

						<div className="px-4 py-5 sm:p-6">
							<div className="grid grid-cols-6 gap-6">
								<InputField
									name="semesterName"
									className="col-span-6 lg:col-span-6"
									label="Semester Name"
									type="text"
								/>

								<InputField
									name="courseName"
									className="col-span-6 lg:col-span-2"
									label="Course Name"
									type="text"
								/>
							</div>
						</div>

						<Button
							// onClick={addSemester}
							label="Add New Semester"
							trailingIcon={
								<svg
									xmlns="http://www.w3.org/2000/svg"
									fill="none"
									viewBox="0 0 24 24"
									width="20"
									height="20"
									strokeWidth={2}
									stroke="currentColor"
									className="mr-2"
								>
									<path
										strokeLinecap="round"
										strokeLinejoin="round"
										d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"
									/>
								</svg>
							}
							onClick={() => console.log('Add new Semester')}
						/>
					</form>
				</section>
			</Container>
		</>
	);
}
