import Sidebar from "src/partials/Sidebar";
import Navbar from "src/partials/Navbar";
import Head from "next/head";
import Button from "src/Components/Button";
import InputField from "src/Components/InputField";

export default function Profile() {
    return (
        <>
            <Head>
                <title>Profile</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/courses.svg" />
            </Head>
            <Navbar />
            <Sidebar />
            <div className="flex flex-col flex-auto flex-shrink-0 min-h-screen transition-all duration-300">
                <div className="h-full grid-flow-col mt-24 mb-20 ml-14 md:ml-64">

                    <div className="flex flex-col items-center justify-center mt-4">

                        <div className="flex flex-col items-center justify-center">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-32 h-32 rounded-full">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
                            </svg>

                            <div className="mt-3 font-medium">
                                <h1 className="text-2xl font-bold text-center">Jese Leos</h1>
                                <div className="text-sm text-center text-gray-500 dark:text-gray-400">Joined in August 2014</div>
                            </div>
                        </div>

                        <div className="mt-6 mb-4 ml-auto mr-5">
                            <Button className="flex p-2 space-x-2 text-base font-bold " onClick={() => { }}>
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
                                </svg>
                                <span>Edit</span>
                            </Button>
                        </div>
                    </div>
                    <form className="flex flex-col justify-center px-4 overflow-hidden">
                        <div className="overflow-hidden shadow sm:rounded-md">
                            <div className="px-4 py-5 sm:p-6">
                                <div className="grid grid-cols-6 gap-6">
                                    <InputField name="firstname" className="col-span-6 lg:col-span-2" label="First Name" type="text" value="Manas" />
                                    <InputField name="middlename" className="col-span-6 lg:col-span-2" label="Middle Name" type="text" />
                                    <InputField name="lastname" className="col-span-6 lg:col-span-2" label="Last Name" type="text" />
                                    <InputField name="email" className="col-span-6 sm:col-span-4" label="Email Address" type="text" />
                                    <InputField name="dateofBirth" className="col-span-6 sm:col-span-4" label="Date of Birth" type="date" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </>
    )
}