import { CalendarDaysIcon } from '@heroicons/react/24/outline';
import Head from 'next/head';
import router from 'next/router';
import React, { useEffect } from 'react';
import { useAuth } from 'src/context/AuthContext';
import Container from 'src/partials/Container';
import Navbar from 'src/partials/Navbar';
import Sidebar from 'src/partials/Sidebar';

export default function ViewTimeTable() {
	const { user } = useAuth();

	useEffect(() => {
		if (user?.userId !== '' && user?.role === 'ADMIN') {
			router.replace('/dashboard');
		}
	}, [user]);
	return (
		<>
			<Head>
				<title>View TimeTable</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/timetable.svg" />
			</Head>
			<Navbar />
			<Sidebar />
			<Container>
				<section className="ml-3 h-full">
					<span className="inline-flex items-center text-2xl font-medium text-primary-800 dark:text-primary-500">
						<CalendarDaysIcon className="m-8 h-8 mr-2" />
						View Timetable
					</span>
				</section>
			</Container>
		</>
	);
}
