import Sidebar from 'src/partials/Sidebar';
import Navbar from 'src/partials/Navbar';
import Head from 'next/head';
import Container from 'src/partials/Container';
import {
	ChartBarIcon,
	MagnifyingGlassIcon,
	PlusCircleIcon,
	UsersIcon,
} from '@heroicons/react/24/outline';
import Link from 'next/link';
import PageMetric from 'src/Components/PageMetric';
import InputField from 'src/Components/InputField';
import { Button } from 'src/Components/Button';
import {
	THead,
	THeaderRowCell,
	THeadCell,
	TBody,
	TDataCell,
	TRow,
} from 'src/Components/TableComponents';

export default function Users() {
	return (
		<>
			<Head>
				<title>Manage Users</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/professors.svg" />
			</Head>
			<Navbar />
			<Sidebar />

			<Container>
				<div className="grid grid-cols-1 gap-2 px-2 sm:grid-cols-2 lg:grid-cols-3">
					<PageMetric
						label="Active"
						// TODO: use state
						value={1}
						logo={
							<ChartBarIcon
								height={30}
								width={30}
								strokeWidth={2}
								className="transition-transform duration-500 ease-in-out transform stroke-current text-primary-800 dark:text-gray-800"
							/>
						}
					/>
					<PageMetric
						label="Total"
						// TODO: use state
						value={1}
						logo={
							<UsersIcon
								height={30}
								width={30}
								strokeWidth={2}
								className="transition-transform duration-500 ease-in-out transform stroke-current text-primary-800 dark:text-gray-800"
							/>
						}
					/>
					<Link
						className="flex items-center justify-between p-3 font-medium border-2 rounded-md shadow-lg text-primary-800 dark:text-white dark:bg-gray-800 dark:border-gray-600 group hover:bg-primary-200 hover:dark:bg-primary-800 lg:-order-1"
						href="/users/new"
					>
						<p className="pl-2 text-xl">Create Users</p>
						<div className="flex items-center justify-center transition-all duration-300 transform bg-white rounded-full w-14 h-14 group-hover:rotate-12">
							<PlusCircleIcon
								height={30}
								width={30}
								strokeWidth={2}
								className="transition-transform duration-500 ease-in-out transform stroke-current text-primary-800 dark:text-gray-800"
							/>
						</div>
					</Link>
				</div>
				<div className="flex flex-col gap-4 p-3 mx-3 mt-4 border-b md:flex-row lg:flex-row dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
					<InputField
						className=""
						label="Filter by username"
						placeholder="User Name"
					/>
					<div className="flex flex-col justify-end">
						<Button
							onClick={() => {
								console.log('Search');
							}}
							label="Search"
							trailingIcon={
								<MagnifyingGlassIcon className="inline-flex w-6 h-6" />
							}
						/>
					</div>
				</div>
				<div className="w-full px-3 overflow-x-auto rounded-sm">
					<table className="w-full">
						<THead>
							<THeaderRowCell>
								<THeadCell>Username</THeadCell>
								<THeadCell>Full name</THeadCell>
								<THeadCell>Role</THeadCell>
							</THeaderRowCell>
						</THead>
						<TBody>
							<TRow>
								<TDataCell colSpan={3} className="text-center">
									No Users created
								</TDataCell>
							</TRow>
						</TBody>
					</table>
				</div>
			</Container>
		</>
	);
}
